version: "2"
services:
  node:
    build: .
    command: yarn dev
    ports:
    - "3000:3000"
    depends_on:
    - mongo
  mongo:
    image: mongo:4.2
    ports:
    - "27017:27017"
    volumes:
    - "./data/mongo/data:/data/db"